CREATE TABLE `github_repos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`externalId` varchar(64) NOT NULL,
	`userId` int NOT NULL,
	`connectorId` int,
	`fullName` varchar(256) NOT NULL,
	`name` varchar(128) NOT NULL,
	`description` text,
	`htmlUrl` text NOT NULL,
	`cloneUrl` text,
	`sshUrl` text,
	`defaultBranch` varchar(128) DEFAULT 'main',
	`isPrivate` int NOT NULL DEFAULT 0,
	`language` varchar(64),
	`starCount` int DEFAULT 0,
	`forkCount` int DEFAULT 0,
	`openIssuesCount` int DEFAULT 0,
	`pushedAt` timestamp,
	`lastSyncAt` timestamp,
	`status` enum('connected','syncing','error','disconnected') NOT NULL DEFAULT 'connected',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `github_repos_id` PRIMARY KEY(`id`),
	CONSTRAINT `github_repos_externalId_unique` UNIQUE(`externalId`)
);
--> statement-breakpoint
CREATE TABLE `webapp_deployments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`externalId` varchar(64) NOT NULL,
	`projectId` int NOT NULL,
	`userId` int NOT NULL,
	`versionLabel` varchar(256),
	`commitSha` varchar(64),
	`commitMessage` text,
	`bundleUrl` text,
	`bundleKey` text,
	`status` enum('building','deploying','live','rolled_back','failed') NOT NULL DEFAULT 'building',
	`buildLog` text,
	`errorMessage` text,
	`screenshotUrl` text,
	`buildDurationSec` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `webapp_deployments_id` PRIMARY KEY(`id`),
	CONSTRAINT `webapp_deployments_externalId_unique` UNIQUE(`externalId`)
);
--> statement-breakpoint
CREATE TABLE `webapp_projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`externalId` varchar(64) NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(256) NOT NULL,
	`description` text,
	`framework` varchar(64) DEFAULT 'react',
	`githubRepoId` int,
	`webappBuildId` int,
	`customDomain` varchar(256),
	`subdomainPrefix` varchar(64),
	`envVars` json,
	`buildCommand` varchar(512) DEFAULT 'npm run build',
	`outputDir` varchar(256) DEFAULT 'dist',
	`installCommand` varchar(512) DEFAULT 'npm install',
	`nodeVersion` varchar(16) DEFAULT '22',
	`deployTarget` enum('manus','github_pages','vercel','netlify') DEFAULT 'manus',
	`publishedUrl` text,
	`deployStatus` enum('idle','building','deploying','live','failed') NOT NULL DEFAULT 'idle',
	`deployError` text,
	`faviconUrl` text,
	`totalPageViews` bigint DEFAULT 0,
	`totalUniqueVisitors` bigint DEFAULT 0,
	`visibility` enum('public','private') DEFAULT 'public',
	`lastDeployedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `webapp_projects_id` PRIMARY KEY(`id`),
	CONSTRAINT `webapp_projects_externalId_unique` UNIQUE(`externalId`)
);
