/**
 * DesktopAppPage — Desktop App Builder
 * Capability #46: Desktop App
 *
 * Generates Tauri configuration and build scripts to package
 * the web app as a native desktop application.
 */
import { useState, useCallback } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { getLoginUrl } from "@/const";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import {
  Monitor, Download, Copy, CheckCircle2, Loader2, LogIn,
  ArrowLeft, Settings, Package, Apple, Laptop,
} from "lucide-react";
import { useLocation } from "wouter";
import { toast } from "sonner";

type Platform = "windows" | "macos" | "linux";
type BuildConfig = {
  appName: string;
  appId: string;
  version: string;
  tauriConfig: string;
  buildScript: string;
  platforms: Platform[];
};

export default function DesktopAppPage() {
  const { isAuthenticated } = useAuth();
  const [, navigate] = useLocation();
  const [appName, setAppName] = useState("Manus Next");
  const [appId, setAppId] = useState("com.manus.next");
  const [version, setVersion] = useState("1.0.0");
  const [platforms, setPlatforms] = useState<Platform[]>(["windows", "macos", "linux"]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [config, setConfig] = useState<BuildConfig | null>(null);

  const togglePlatform = useCallback((p: Platform) => {
    setPlatforms((prev) =>
      prev.includes(p) ? prev.filter((x) => x !== p) : [...prev, p]
    );
  }, []);

  const generateConfig = useCallback(async () => {
    if (!appName.trim()) {
      toast.error("Enter an app name");
      return;
    }
    setIsGenerating(true);

    const tauriConfig = JSON.stringify({
      "$schema": "../node_modules/@tauri-apps/cli/schema.json",
      build: {
        beforeBuildCommand: "pnpm build",
        beforeDevCommand: "pnpm dev",
        devPath: "http://localhost:5173",
        distDir: "../dist",
      },
      package: {
        productName: appName,
        version: version,
      },
      tauri: {
        allowlist: {
          all: false,
          shell: { all: false, open: true },
          dialog: { all: true },
          fs: { all: true, scope: ["$APPDATA/**", "$DOWNLOAD/**"] },
          http: { all: true, scope: ["https://**"] },
          notification: { all: true },
          clipboard: { all: true },
        },
        bundle: {
          active: true,
          identifier: appId,
          icon: [
            "icons/32x32.png",
            "icons/128x128.png",
            "icons/128x128@2x.png",
            "icons/icon.icns",
            "icons/icon.ico",
          ],
          targets: platforms.includes("windows")
            ? ["nsis", "msi"]
            : platforms.includes("macos")
            ? ["dmg", "app"]
            : ["deb", "appimage"],
        },
        security: {
          csp: null,
        },
        windows: [
          {
            fullscreen: false,
            resizable: true,
            title: appName,
            width: 1200,
            height: 800,
            minWidth: 800,
            minHeight: 600,
          },
        ],
      },
    }, null, 2);

    const buildScript = `#!/bin/bash
# ${appName} Desktop Build Script
# Generated by Manus Next Desktop App Builder

set -e

echo "=== ${appName} Desktop Build ==="
echo "Version: ${version}"
echo "Platforms: ${platforms.join(", ")}"

# Prerequisites check
command -v cargo >/dev/null 2>&1 || { echo "Rust/Cargo required. Install from https://rustup.rs"; exit 1; }
command -v pnpm >/dev/null 2>&1 || { echo "pnpm required. Install with: npm i -g pnpm"; exit 1; }

# Install Tauri CLI
pnpm add -D @tauri-apps/cli @tauri-apps/api

# Initialize Tauri (if not already)
if [ ! -d "src-tauri" ]; then
  pnpm tauri init
fi

# Copy generated config
cp tauri.conf.json src-tauri/tauri.conf.json

# Build for each platform
${platforms.map((p) => {
  if (p === "windows") return 'echo "Building for Windows..."\npnpm tauri build --target x86_64-pc-windows-msvc';
  if (p === "macos") return 'echo "Building for macOS..."\npnpm tauri build --target aarch64-apple-darwin\npnpm tauri build --target x86_64-apple-darwin';
  return 'echo "Building for Linux..."\npnpm tauri build --target x86_64-unknown-linux-gnu';
}).join("\n\n")}

echo "=== Build complete! ==="
echo "Installers are in src-tauri/target/release/bundle/"
`;

    setConfig({
      appName,
      appId,
      version,
      tauriConfig,
      buildScript,
      platforms,
    });

    setIsGenerating(false);
    toast.success("Desktop app configuration generated!");
  }, [appName, appId, version, platforms]);

  const copyToClipboard = useCallback((text: string, label: string) => {
    navigator.clipboard.writeText(text);
    toast.success(`${label} copied to clipboard`);
  }, []);

  const downloadConfig = useCallback(() => {
    if (!config) return;
    const blob = new Blob([config.tauriConfig], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "tauri.conf.json";
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Configuration downloaded");
  }, [config]);

  if (!isAuthenticated) {
    return (
      <div className="h-full flex items-center justify-center">
        <Card className="max-w-sm">
          <CardContent className="p-6 text-center">
            <Monitor className="w-12 h-12 text-primary mx-auto mb-4" />
            <h2 className="text-lg font-semibold mb-2">Desktop App Builder</h2>
            <p className="text-muted-foreground mb-4">Sign in to build desktop apps.</p>
            <Button onClick={() => (window.location.href = getLoginUrl())}>
              <LogIn className="w-4 h-4 mr-2" /> Sign In
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="h-full overflow-y-auto">
      <div className="max-w-4xl mx-auto px-4 py-6">
        <div className="flex items-center gap-3 mb-6">
          <Button variant="ghost" size="icon" onClick={() => navigate("/")}>
            <ArrowLeft className="w-4 h-4" />
          </Button>
          <div>
            <h1 className="text-xl font-semibold text-foreground" style={{ fontFamily: "var(--font-heading)" }}>
              Desktop App Builder
            </h1>
            <p className="text-sm text-muted-foreground">Package your web app as a native desktop application</p>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Configuration */}
          <div className="space-y-4">
            <Card className="bg-card border-border">
              <CardHeader className="pb-3">
                <CardTitle className="text-sm flex items-center gap-2">
                  <Settings className="w-4 h-4 text-primary" /> App Configuration
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div>
                  <label className="text-xs text-muted-foreground mb-1 block">App Name</label>
                  <Input value={appName} onChange={(e) => setAppName(e.target.value)} />
                </div>
                <div>
                  <label className="text-xs text-muted-foreground mb-1 block">Bundle ID</label>
                  <Input value={appId} onChange={(e) => setAppId(e.target.value)} />
                </div>
                <div>
                  <label className="text-xs text-muted-foreground mb-1 block">Version</label>
                  <Input value={version} onChange={(e) => setVersion(e.target.value)} />
                </div>
              </CardContent>
            </Card>

            <Card className="bg-card border-border">
              <CardHeader className="pb-3">
                <CardTitle className="text-sm flex items-center gap-2">
                  <Package className="w-4 h-4 text-primary" /> Target Platforms
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="flex gap-3">
                  {([
                    { id: "windows" as Platform, label: "Windows", icon: Laptop },
                    { id: "macos" as Platform, label: "macOS", icon: Apple },
                    { id: "linux" as Platform, label: "Linux", icon: Monitor },
                  ]).map((p) => (
                    <button
                      key={p.id}
                      onClick={() => togglePlatform(p.id)}
                      className={`flex-1 flex flex-col items-center gap-2 p-4 rounded-xl border transition-all ${
                        platforms.includes(p.id)
                          ? "border-primary bg-primary/5"
                          : "border-border hover:border-primary/30"
                      }`}
                    >
                      <p.icon className={`w-6 h-6 ${platforms.includes(p.id) ? "text-primary" : "text-muted-foreground"}`} />
                      <span className="text-xs font-medium">{p.label}</span>
                      {platforms.includes(p.id) && <CheckCircle2 className="w-3.5 h-3.5 text-primary" />}
                    </button>
                  ))}
                </div>
                <Button onClick={generateConfig} disabled={isGenerating || platforms.length === 0} className="w-full mt-4">
                  {isGenerating ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Package className="w-4 h-4 mr-2" />}
                  Generate Configuration
                </Button>
              </CardContent>
            </Card>
          </div>

          {/* Output */}
          <div className="space-y-4">
            {!config ? (
              <Card className="bg-card border-border">
                <CardContent className="p-8 text-center">
                  <Monitor className="w-12 h-12 text-muted-foreground mx-auto mb-3" />
                  <p className="text-sm text-muted-foreground">Configure and generate to see output</p>
                </CardContent>
              </Card>
            ) : (
              <>
                <Card className="bg-card border-border">
                  <CardHeader className="pb-3">
                    <div className="flex items-center justify-between">
                      <CardTitle className="text-sm">tauri.conf.json</CardTitle>
                      <div className="flex gap-1">
                        <Button variant="ghost" size="sm" onClick={() => copyToClipboard(config.tauriConfig, "Config")}>
                          <Copy className="w-3 h-3 mr-1" /> Copy
                        </Button>
                        <Button variant="ghost" size="sm" onClick={downloadConfig}>
                          <Download className="w-3 h-3 mr-1" /> Download
                        </Button>
                      </div>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <pre className="bg-muted/50 rounded-lg p-3 text-xs overflow-x-auto max-h-60 overflow-y-auto">
                      <code>{config.tauriConfig}</code>
                    </pre>
                  </CardContent>
                </Card>

                <Card className="bg-card border-border">
                  <CardHeader className="pb-3">
                    <div className="flex items-center justify-between">
                      <CardTitle className="text-sm">build.sh</CardTitle>
                      <Button variant="ghost" size="sm" onClick={() => copyToClipboard(config.buildScript, "Build script")}>
                        <Copy className="w-3 h-3 mr-1" /> Copy
                      </Button>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <pre className="bg-muted/50 rounded-lg p-3 text-xs overflow-x-auto max-h-60 overflow-y-auto">
                      <code>{config.buildScript}</code>
                    </pre>
                  </CardContent>
                </Card>

                <Card className="bg-card border-border">
                  <CardContent className="p-4">
                    <div className="flex items-center gap-2 mb-2">
                      <CheckCircle2 className="w-4 h-4 text-muted-foreground" />
                      <span className="text-sm font-medium text-foreground">Ready to Build</span>
                    </div>
                    <p className="text-xs text-muted-foreground">
                      Download the config, place it in your project, and run the build script.
                      Requires Rust and Tauri CLI installed locally.
                    </p>
                    <div className="flex flex-wrap gap-1.5 mt-2">
                      {config.platforms.map((p) => (
                        <Badge key={p} variant="secondary" className="text-[10px]">{p}</Badge>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
